---
title: "Exercises"
output: pdf_document
---

## 02 - Open science framework

1. Make a project on the [open science framework](https://osf.io/).  Call it 'Best practice workshop'
2. Add a description 'Example project'
3. Edit the wiki and add a link to the paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5366108/
4. Link your project our project https://osf.io/zgwj2/ (go to components > link project > search "Data Analysis Best Practice")
5. Add tags to your project, e.g. 'reproduction', 'DILI', 'workshop'

## 04 - pre-registration
1. Navigate to https://cos.io/rr/ and see if you can find a journal in your area that allows registered reports. 
2. Navigate to http://help.osf.io/m/registrations.  Find the template registration form which is eligible for the pre-registration challenge.  What is topic 8?

## 0X - Markdown and RMarkdown
### Markdown
1. Go to [goo.gl/Kx1ys2] (a document I created at hackMD.io - like google docs for Markdown - you can link your login to your GitHub account)
2. Sign up/log in
3. Spend 5-10 minutes playing with Markdown.

### RMarkdown
1. Open RStudio
2. Create a new RMarkdown file (File>New File>R) (an example file will be generated)
3. Run and individual code snippet from the generated file.
4. Knit and convert the document into a PDF.

1. Later...

## 05 - version control 

1. Navigate to https://github.com/RobertArbon/analysis_best_practice/exercises/version_control.Rmd
2. Follow the instructions and questions up to 'Your first commit!'

## 06 - dev environment

1. Configure your RStudio with the following layout: 
  1. Bottom left: `Console` and `Terminal`
  2. Top left: `Source`
  3. Top right: `Environment`, `History`, `VCS`
  4. Bottom right: `Files`, `Plots`, `Packages`, `Help`, `Viewer`

2. Check the 'Options'> 'RMarkdown': What directory are code chunks evaluted in?  Can you change this? What does this mean?

3. Look in the 'History' pane - try and run a previous command in the console without typing it out. 

## 08 - tidy data

1. In `exercises/analysis.Rmd` add code to the empty code chunks in the sections **Data loading** and **Tidy data**

## 09 - Analysis 

1. In `exercises/analysis.Rmd` add code to the empty code chunks in the sections **Analysis**. 
2. `knit` the document to a `pdf` and upload it to the project on `osf.io`.
3. **EXTENTION**: Complete the `baseline-comparison.Rmd` workbook, `knit` to `pdf` and upload the `osf.io`.  NB: it's long and difficult, but good practice for doing manipulations in R. 




